/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Icon: typeof import('./src/components/Icon/index.vue')['default']
    Progress: typeof import('./src/components/Progress/index.vue')['default']
    ProgressMask: typeof import('./src/components/ProgressMask/index.vue')['default']
  }
}
